# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v2.0.1'  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-json
    -   id: detect-private-key
    -   id: mixed-line-ending

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-check-mock-methods
    -   id: python-use-type-annotations
    -   id: text-unicode-replacement-char

-   repo: local
    hooks:
    -   id: unittest_test_pattern_1
        name: unittest
        entry: python -m unittest discover
        language: system
        'types': [python]
        args: [--start-directory=./tests, --pattern=test_*.py]
        additional_dependencies: []
        pass_filenames: false
        verbose: true
    -   id: unittest_test_pattern_2
        name: unittest
        entry: python -m unittest discover
        language: system
        'types': [python]
        args: [--start-directory=./tests, --pattern=ut_*.py]
        additional_dependencies: []
        pass_filenames: false
        verbose: true
