DEFAULT_DATE_FORMAT = "%Y-%m-%d"
TIME_FORMAT_WITH_MS_PRECISION = "%H:%M:%S.%f"
DATE_TIME_FORMAT_WITH_MS_PRECISION = DEFAULT_DATE_FORMAT + " " + TIME_FORMAT_WITH_MS_PRECISION
CCXT_DATA_COLUMNS = ["datetime", "open", "high", "low", "close", "volume", "openinterest"]
DATETIME_COL, OPEN_COL, HIGH_COL, LOW_COL, CLOSE_COL, VOLUME_COL, OPEN_INTEREST_COL = range(len(CCXT_DATA_COLUMNS))

BT_CCXT__CASH_TRANSFER_WAIT_TIME__IN_SECONDS = 1.0
CASH_DIGITS = 4
MAX_LIVE_EXCHANGE_RETRIES = 5
VALUE_DIGITS = 4
